name: Build Push and Deploy dev

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-dev:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - 
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - 
        name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ticketing

      - 
        name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f auth-depl.yaml && kubectl apply -f auth-mongo-depl.yaml && kubectl apply -f ingress-srv.yaml 
          working-directory: infra/dev
      - 
        name: Verify deployment
        run: kubectl rollout status deployment/auth-dev
